namespace: default
resources:
  - backend.yaml
  - frontend.yaml
  - nginx.yaml
  - mariadb.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  - name: init-db
    files:
      - configs/init.sql

